# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'git@gitee.com:yizhuangwuyanzu/QQSpecs.git'

target 'XiMaLaShi' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XiMaLaShi

pod 'QQFMBase'

end
